[alembic]
# path to migration scripts
script_location = app/db/migrations

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
timezone = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file as a python script,
# instead of importing it.
# script_as_module = false

# revision environment configuration
# sqlalchemy.url = driver://user:pass@localhost/dbname
sqlalchemy.url = %(DATABASE_URL)s

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualifier = %(levelname)s

[logger_sqlalchemy]
level = WARN
handlers =
qualifier = %(levelname)s

[logger_alembic]
level = INFO
handlers =
qualifier = %(levelname)s

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
qualifier = %(levelname)s

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %%H:%%M:%%S
